---
# file: tasks/install.yml
#
# installation tasks.
#

- include_tasks: unzip.yml

- include_tasks: tar.yml

- name: download ldc
  get_url:
    url: "https://github.com/ldc-developers/ldc/releases/download/v{{ ldc_version }}/ldc2-{{ ldc_version }}-linux-x86_64.tar.xz"
    dest: "/tmp/ldc2-{{ ldc_version }}-linux-x86_64.tar.xz"

- name: unzip ldc
  unarchive:
    src: "/tmp/ldc2-{{ ldc_version }}-linux-x86_64.tar.xz"
    dest: "{{ ldc_install_dir }}"
    creates: "{{ ldc_install_dir }}/ldc2-{{ ldc_version }}-linux-x86_64"
    copy: false
